apiVersion: apps/v1
kind: Deployment
metadata:
  name: mt-spring-deploy
  namespace: mt-spring-nms
  labels:
    app: mt-spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mt-spring
  template:
    metadata:
      labels:
        app: mt-spring
    spec:
      containers:
        - name: mt-spring
          image: kangyejini/web-app:3c88be776153cb0a061eb30be211178ab3ea09f7
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: default   # application.yml만 읽도록 강제
          envFrom:
            - configMapRef:
                name: mt-server-config
            - secretRef:
                name: mt-spring-scr
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
              ephemeral-storage: "100Mi"
            limits:
              memory: "1Gi"
              cpu: "500m"
              ephemeral-storage: "500Mi"   # 최대 사용량
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 5
      restartPolicy: Always