apiVersion: apps/v1
kind: Deployment
metadata:
  name: mt-spring-deployment
  namespace: mt-spring-nms
spec:
  selector:
    matchLabels:
      app: mt-spring
  template:
    metadata:
      labels:
        app: mt-spring
    spec:
      serviceAccountName: mt-spring-sa
      containers:
        - name: mt-spring
          image: kangyejini/web-app:df6454a2bc15d0e64099f4af7880b71050bd47e2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: mt-server-config
            - secretRef:
                name: mt-spring-scr
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"