apiVersion: v1
kind: Service
metadata:
  name: mt-spring-svc
  namespace: mt-spring-nms
  labels:
    app: mt-spring
spec:
  type: ClusterIP
  selector:
    app: mt-spring
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080